rookie:
  port: 9000
  bossThreadSize: 1
  workThreadSize: 8
  redis:
    mode: single
    database: 1
    password: 111111
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 192.168.121.24:6379